-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 02:29:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laravel_master
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel_master
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel_master` DEFAULT CHARACTER SET utf8 ;
USE `laravel_master` ;

-- -----------------------------------------------------
-- Table `laravel_master`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_master`.`USERS` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NULL,
  `name` VARCHAR(100) NULL,
  `surname` VARCHAR(200) NULL,
  `nick` VARCHAR(100) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `remember_token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_master`.`IMAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_master`.`IMAGES` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `user_id` INT(255) NULL,
  `image_path` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_images_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `laravel_master`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_master`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_master`.`COMMENTS` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `user_id` INT(255) NULL,
  `image_id` INT(255) NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `laravel_master`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_images`
    FOREIGN KEY (`image_id`)
    REFERENCES `laravel_master`.`IMAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_master`.`LIKES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_master`.`LIKES` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `user_id` INT(255) NULL,
  `image_id` INT(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_likes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `laravel_master`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_images`
    FOREIGN KEY (`image_id`)
    REFERENCES `laravel_master`.`IMAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
